services:
  dunia-app:
    container_name: dunia-app
    image: tpng:latest
    environment:
      SECRET_KEY: huhuhaha 
      DB_NAME: dunia
      DB_HOST: local-dev-postgresql-1
      DB_PORT: 5432
      DB_USER: dalang
      DB_PASSWORD:
    ports:
      - "8000:8000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true