[project]
name = "hellodunia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.5",
    "granian>=1.7.6",
    "nodejs>=0.1.1",
    "tailwind>=3.1.5b0",
]
