# Generated by Django 5.1.5 on 2025-02-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_product_description_product_stock_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
