# Generated by Django 5.1.5 on 2025-02-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hellodunia/mediaproducts/'),
        ),
    ]
